import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import './globals.css'
import { Providers } from '@/store/Providers'

const raleway = Raleway({
  weight: ['300', '400', '700', '900'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${raleway.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
